### ISSUE TITLE
Text search not working properly

### ISSUE THREAD

**Issue by acosonic** [jkraemer/redmine_postgresql_search#4]
If I try searching for "bobo" I get no result, but if I search for "bobo123" I do get result.

Expected result (and working on mysql) is that bobo returns results with bobo123 as well.

**Comment by jkraemer** [comment]
Did you try searching for `bobo*` ?

**Comment by acosonic** [comment]
I think I did. I was testing both dmsf plugin search inside documents and this, and I'm not sure. Now I've removed plugin.

**Comment by jkraemer** [comment]
prefix search using `*` works for me, thus closing this.
